<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNHkagRN\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNHkagRN/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNHkagRN.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNHkagRN\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNHkagRN\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NHkagRN',
    'container.build_id' => 'd84532b9',
    'container.build_time' => 1646217229,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNHkagRN');
