<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMUibsQn\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMUibsQn/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMUibsQn.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMUibsQn\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMUibsQn\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MUibsQn',
    'container.build_id' => 'e78b77ab',
    'container.build_time' => 1646773875,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMUibsQn');
